# Generated by Django 3.0.2 on 2020-01-18 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=64)),
                ('board_description', models.CharField(max_length=128)),
                ('board_created', models.DateTimeField(auto_now_add=True, verbose_name='date and time the board was created')),
                ('board_modified', models.DateTimeField(auto_now=True, verbose_name='date and time the board was most recently modified')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=64)),
                ('topic_text', models.TextField(max_length=512)),
                ('topic_created', models.DateTimeField(auto_now_add=True, verbose_name='date and time the Topic was created')),
                ('topic_modified', models.DateTimeField(auto_now=True, verbose_name='date and time the Topic was most recently modified')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=512)),
                ('comment_created', models.DateTimeField(auto_now_add=True, verbose_name='date and time the Comment was created')),
                ('comment_modified', models.DateTimeField(auto_now=True, verbose_name='date and time the Comment was most recently modified')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic')),
            ],
        ),
    ]
